package entity;
// Generated Apr 21, 2018 4:02:45 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AttendanceReport generated by hbm2java
 */
@Entity
@Table(name="attendance_report"
    ,catalog="db_school_attendance"
)
public class AttendanceReport  implements java.io.Serializable {


     private Integer attendanceReportId;
     private Month month;
     private Student student;
     private StudentClass studentClass;
     private int countPresents;
     private int countAbsents;

    public AttendanceReport() {
    }

    public AttendanceReport(Month month, Student student, StudentClass studentClass, int countPresents, int countAbsents) {
       this.month = month;
       this.student = student;
       this.studentClass = studentClass;
       this.countPresents = countPresents;
       this.countAbsents = countAbsents;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="attendance_report_id", unique=true, nullable=false)
    public Integer getAttendanceReportId() {
        return this.attendanceReportId;
    }
    
    public void setAttendanceReportId(Integer attendanceReportId) {
        this.attendanceReportId = attendanceReportId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="month_id", nullable=false)
    public Month getMonth() {
        return this.month;
    }
    
    public void setMonth(Month month) {
        this.month = month;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class_id", nullable=false)
    public StudentClass getStudentClass() {
        return this.studentClass;
    }
    
    public void setStudentClass(StudentClass studentClass) {
        this.studentClass = studentClass;
    }

    
    @Column(name="count_presents", nullable=false)
    public int getCountPresents() {
        return this.countPresents;
    }
    
    public void setCountPresents(int countPresents) {
        this.countPresents = countPresents;
    }

 @Column(name="count_absents", nullable=false)
    public int getCountAbsents() {
        return this.countAbsents;
    }
    
    public void setCountAbsents(int countAbsents) {
        this.countAbsents = countAbsents;
    }


}


