package entity;
// Generated Apr 21, 2018 4:02:45 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClassCounter generated by hbm2java
 */
@Entity
@Table(name="class_counter"
    ,catalog="db_school_attendance"
)
public class ClassCounter  implements java.io.Serializable {


     private Integer classCountId;
     private Month month;
     private StudentClass studentClass;
     private int classCount;

    public ClassCounter() {
    }

    public ClassCounter(Month month, StudentClass studentClass, int classCount) {
       this.month = month;
       this.studentClass = studentClass;
       this.classCount = classCount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="class_count_id", unique=true, nullable=false)
    public Integer getClassCountId() {
        return this.classCountId;
    }
    
    public void setClassCountId(Integer classCountId) {
        this.classCountId = classCountId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="month_id", nullable=false)
    public Month getMonth() {
        return this.month;
    }
    
    public void setMonth(Month month) {
        this.month = month;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class_id", nullable=false)
    public StudentClass getStudentClass() {
        return this.studentClass;
    }
    
    public void setStudentClass(StudentClass studentClass) {
        this.studentClass = studentClass;
    }

    
    @Column(name="class_count", nullable=false)
    public int getClassCount() {
        return this.classCount;
    }
    
    public void setClassCount(int classCount) {
        this.classCount = classCount;
    }




}


