package entity;
// Generated Apr 21, 2018 4:02:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StudentClass generated by hbm2java
 */
@Entity
@Table(name="student_class"
    ,catalog="db_school_attendance"
)
public class StudentClass  implements java.io.Serializable {


     private Integer classId;
     private String name;
     private Set<Attendance> attendances = new HashSet<Attendance>(0);
     private Set<Student> students = new HashSet<Student>(0);
     private Set<ClassCounter> classCounters = new HashSet<ClassCounter>(0);
     private Set<AttendanceReport> attendanceReports = new HashSet<AttendanceReport>(0);

    public StudentClass() {
    }

	
    public StudentClass(String name) {
        this.name = name;
    }
    public StudentClass(String name, Set<Attendance> attendances, Set<Student> students, Set<ClassCounter> classCounters, Set<AttendanceReport> attendanceReports) {
       this.name = name;
       this.attendances = attendances;
       this.students = students;
       this.classCounters = classCounters;
       this.attendanceReports = attendanceReports;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="class_id", unique=true, nullable=false)
    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentClass")
    public Set<Attendance> getAttendances() {
        return this.attendances;
    }
    
    public void setAttendances(Set<Attendance> attendances) {
        this.attendances = attendances;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentClass")
    public Set<Student> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<Student> students) {
        this.students = students;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentClass")
    public Set<ClassCounter> getClassCounters() {
        return this.classCounters;
    }

    @Override
    public String toString() {
        return "StudentClass{" + "classId=" + classId + ", name=" + name + '}';
    }
    
    public void setClassCounters(Set<ClassCounter> classCounters) {
        this.classCounters = classCounters;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentClass")
    public Set<AttendanceReport> getAttendanceReports() {
        return this.attendanceReports;
    }
    
    public void setAttendanceReports(Set<AttendanceReport> attendanceReports) {
        this.attendanceReports = attendanceReports;
    }




}


