package entity;
// Generated Apr 21, 2018 4:02:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="db_school_attendance"
)
public class Student  implements java.io.Serializable {


     private Integer studentId;
     private StudentClass studentClass;
     private String studentName;
     private int roll;
     private Set<Attendance> attendances = new HashSet<Attendance>(0);
     private Set<AttendanceReport> attendanceReports = new HashSet<AttendanceReport>(0);

    public Student() {
    }

	
    public Student(StudentClass studentClass, String studentName, int roll) {
        this.studentClass = studentClass;
        this.studentName = studentName;
        this.roll = roll;
    }
    public Student(StudentClass studentClass, String studentName, int roll, Set<Attendance> attendances, Set<AttendanceReport> attendanceReports) {
       this.studentClass = studentClass;
       this.studentName = studentName;
       this.roll = roll;
       this.attendances = attendances;
       this.attendanceReports = attendanceReports;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="student_id", unique=true, nullable=false)
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class_id", nullable=false)
    public StudentClass getStudentClass() {
        return this.studentClass;
    }
    
    public void setStudentClass(StudentClass studentClass) {
        this.studentClass = studentClass;
    }

    
    @Column(name="student_name", nullable=false, length=45)
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    
    @Column(name="roll", nullable=false)
    public int getRoll() {
        return this.roll;
    }
    
    public void setRoll(int roll) {
        this.roll = roll;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="student")
    public Set<Attendance> getAttendances() {
        return this.attendances;
    }
    
    public void setAttendances(Set<Attendance> attendances) {
        this.attendances = attendances;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="student", cascade = CascadeType.ALL)
    public Set<AttendanceReport> getAttendanceReports() {
        return this.attendanceReports;
    }
    
    public void setAttendanceReports(Set<AttendanceReport> attendanceReports) {
        this.attendanceReports = attendanceReports;
    }

    @Override
    public String toString() {
        return "Student{" + "studentId=" + studentId + ", studentName=" + studentName + ", roll=" + roll + '}';
    }




}


